language: nodejs
node_js:
  - 12

branches:
  only:
    - master
    - next
    - /^v\d+\.\d+\.\d+$/

before_script:
  - yarn

script:
  - yarn build
  - yarn lint
  - yarn test

after_success:
  - yarn pack

before_deploy:
  - git config --global user.email ${GITHUB_EMAIL}
  - git config --global user.name ${GITHUB_USER}
  - git remote set-url origin "https://${GITHUB_TOKEN}@github.com/atomixdesign/nodepay.git" > /dev/null 2>&1
  - git checkout master
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null

deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: "atomixdesign-nodepay-*.tgz"
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script: "yarn run lerna publish from-package"
    skip_cleanup: true
    on:
      branch: master
